# Generated by Django 6.0.1 on 2026-01-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_photo', models.ImageField(upload_to='hero/')),
                ('quote', models.CharField(max_length=300)),
                ('blocks', models.JSONField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='ContentBlock',
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
