# Generated by Django 6.0.1 on 2026-01-24 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0003_bio_bioitem_delete_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='biography.bio')),
            ],
        ),
    ]
