# Generated by Django 6.0.1 on 2026-02-07 09:33

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0007_alter_bio_main_photo_alter_bioitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioitem',
            name='image_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bioitem',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bioitem',
            name='item_type',
            field=models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video')], max_length=10),
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('description', models.TextField(blank=True, null=True)),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='biography.bio')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('url', models.URLField()),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='biography.bio')),
            ],
        ),
    ]
