# Generated by Django 6.0.1 on 2026-02-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0008_bioitem_image_description_bioitem_youtube_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='bio',
        ),
        migrations.DeleteModel(
            name='GalleryPhoto',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
