# Generated by Django 6.0.1 on 2026-01-24 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0002_biography_delete_contentblock_delete_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('main_photo', models.ImageField(upload_to='bio/main_photos/')),
                ('quote', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo')], max_length=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bio/items/')),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='biography.bio')),
            ],
        ),
        migrations.DeleteModel(
            name='Biography',
        ),
    ]
