# Generated by Django 6.0.1 on 2026-01-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0004_achievement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
