# Generated by Django 6.0.1 on 2026-01-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0005_delete_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='main_photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bioitem',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
