# Generated by Django 6.0.1 on 2026-01-26 14:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0006_alter_bio_main_photo_alter_bioitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='main_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='bioitem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
